---
title: "List of R packages for Ecology"
description: |
 Here is a list (clearly incomplete) of R packages that are focused on Ecology!
site: distill::distill_website
---
Feel free to add to the list by sending me a pull request or adding an issue (https://github.com/DrMattG/REcol-verse)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

```{r, echo=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(here)

pkgs <- readRDS(paste0(here(),"/pkgs.rds"))

```

# R packages

```{r}
pkgs_short<-pkgs %>% 
  select(-Score, -GO) %>% 
  mutate("Source"="packagefinder")

pkgs_short[nrow(pkgs_short) + 1,]<-c("MetaboAnalystR"," An R Package for Comprehensive Analysis of Metabolomics Data","MetaboAnalystR 3.0 contains the R functions and libraries underlying the popular MetaboAnalyst web server, including metabolomic data analysis, visualization, and functional interpretation. The package is synchronized with the MetaboAnalyst web server. After installing and loading the package, users will be able to reproduce the same results from their local computers using the corresponding R command history downloaded from MetaboAnalyst web site, thereby achieving maximum flexibility and reproducibility.

The version 3.0 aims to improve the current global metabolomics workflow by implementing a fast parameter optimization algorithm for peak picking, and automated identification of the most suitable method for batch effect correction from 12 well-established approaches. In addition, more support for functional interpretation directly from m/z peaks via mummichog2 (PMID: 23861661), and a new pathway-based method to integrate multi'omics data has been added. To demonstrate this new functionality, we provide the \"MetaboAnalystR 3.0 Workflow: Towards an Optimized Workflow for Global Metabolomics\" vignette, available here as a PDF. In this vignette, we perform end-to-end metabolomics data analysis on the full batch of clinical IBD samples.","volePhD") 

pkgs_short[nrow(pkgs_short) + 1,]<-c("camtrapR"," Camera Trap Data Management and Preparation of Occupancy and Spatial Capture-Recapture Analyses","See the Article in Methods in Ecology and Evolution <https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12600> for an overview of the package. The four package vignettes provide examples for the entire workflow.","volePhD") 

pkgs_short[nrow(pkgs_short) + 1,]<-c("animaltracker"," Spatial-temporal analysis and visualisation of animal movement data","Utilities for spatial-temporal analysis and visualization of animal (e.g. cattle)
tracking data. The core feature is a 'shiny' web application for customized processing
of GPS logs, including features for data augmentation (e.g. elevation lookup), data selection,
export, plotting, and statistical summaries. A data validation application allows for side-by-side
comparison via time series plots and extreme value detection described by
J.P. van Brakel <https://stackoverflow.com/questions/22583391/peak-signal-detection-inrealtime-timeseries-data/>.","volePhD") 



pkgs_short[nrow(pkgs_short) + 1,]<-c("dismo"," Species distribution modelling","Functions for species distribution modeling, that is, predicting entire geographic distributions form occurrences at a number of sites and the environment at these sites","StatsForBios") 

pkgs_short[nrow(pkgs_short) + 1,]<-c("wallace"," Wallace is a modular platform for reproducible modeling of species niches and distributions, written in R","Wallace is a modular platform for reproducible modeling of species niches and distributions, written in R. The application guides users through a complete analysis, from the acquisition of data to visualizing model predictions on an interactive map, thus bundling complex workflows into a single, streamlined interface.","StatsForBios")

pkgs_short[nrow(pkgs_short) + 1,]<-c("spocc","A programmatic interface to many species occurrence data sources","At rOpenSci, we have been writing R packages to interact with many sources of species occurrence data, including GBIF, Vertnet, BISON, iNaturalist, the Berkeley ecoengine, and eBird. Other databases are out there as well, which we can pull in. spocc is an R package to query and collect species occurrence data from many sources. The goal is to to create a seamless search experience across data sources, as well as creating unified outputs across data sources.

spocc currently interfaces with nine major biodiversity repositories

Global Biodiversity Information Facility (GBIF) (via rgbif) GBIF is a government funded open data repository with several partner organizations with the express goal of providing access to data on Earth's biodiversity. The data are made available by a network of member nodes, coordinating information from various participant organizations and government agencies.

Berkeley Ecoengine (via ecoengine) The ecoengine is an open API built by the Berkeley Initiative for Global Change Biology. The repository provides access to over 3 million specimens from various Berkeley natural history museums. These data span more than a century and provide access to georeferenced specimens, species checklists, photographs, vegetation surveys and resurveys and a variety of measurements from environmental sensors located at reserves across University of California's natural reserve system.

iNaturalist iNaturalist provides access to crowd sourced citizen science data on species observations.

VertNet (via rvertnet) Similar to rgbif, ecoengine, and rbison (see below), VertNet provides access to more than 80 million vertebrate records spanning a large number of institutions and museums primarly covering four major disciplines (mammology, herpetology, ornithology, and icthyology).

Biodiversity Information Serving Our Nation (via rbison) Built by the US Geological Survey's core science analytic team, BISON is a portal that provides access to species occurrence data from several participating institutions.

eBird (via rebird) ebird is a database developed and maintained by the Cornell Lab of Ornithology and the National Audubon Society. It provides real-time access to checklist data, data on bird abundance and distribution, and communtiy reports from birders.

iDigBio (via ridigbio) iDigBio facilitates the digitization of biological and paleobiological specimens and their associated data, and houses specimen data, as well as providing their specimen data via RESTful web services.

OBIS OBIS (Ocean Biogeographic Information System) allows users to search marine species datasets from all of the world's oceans.

Atlas of Living Australia ALA (Atlas of Living Australia) contains information on all the known species in Australia aggregated from a wide range of data providers: museums, herbaria, community groups, government departments, individuals and universities; it contains more than 50 million occurrence records.

The inspiration for this comes from users requesting a more seamless experience across data sources, and from our work on a similar package for taxonomy data (taxize).

BEWARE: In cases where you request data from multiple providers, especially when including GBIF, there could be duplicate records since many providers' data eventually ends up with GBIF. See ?spocc_duplicates, after installation, for more.","StatsForBios")


pkgs_short[nrow(pkgs_short) + 1,]<-c("marked","Mark-Recapture Analysis for Survival and Abundance Estimation","Functions for fitting various models to capture-recapture data
including mixed-effects Cormack-Jolly-Seber(CJS) and multistate models and
the multi-variate state model structure for survival
estimation and POPAN structured Jolly-Seber models for abundance estimation.
There are also Hidden Markov model (HMM) implementations of CJS and multistate
models with and without state uncertainty and a simulation capability for HMM
models.","samdeanscience")

pkgs_short[nrow(pkgs_short) + 1,]<-c("unmarked","Models for Data from Unmarked Animals","Fits hierarchical models of animal abundance and occurrence to data collected using survey methods such as point counts, site occupancy sampling, distance sampling, removal sampling, and double observer sampling. Parameters governing the state and observation processes can be modeled as functions of covariates.","samdeanscience")

pkgs_short[nrow(pkgs_short) + 1,]<-c("Rmark","R Code for Mark Analysis","An interface to the software package MARK that constructs input files for MARK and extracts the output. MARK was developed by Gary White
and is freely available at <http://www.phidot.org/software/mark/downloads/>
but is not open source.","samdeanscience")

pkgs_short[nrow(pkgs_short) + 1,]<-c("ctmm","Continuous-Time Movement Modeling","Functions for identifying, fitting, and applying continuous-space, continuoustime stochastic movement models to animal tracking data.
The package is described in Calabrese et al (2016) <doi:10.1111/2041-
210X.12559>, with models and methods based on those introduced in
Fleming & Calabrese et al (2014) <doi:10.1086/675504>,
Fleming et al (2014) <doi:10.1111/2041-210X.12176>,
Fleming et al (2015) <doi:10.1103/PhysRevE.91.032107>,
Fleming et al (2015) <doi:10.1890/14-2010.1>,
Fleming et al (2016) <doi:10.1890/15-1607>,
Péron & Fleming et al (2016) <doi:10.1186/s40462-016-0084-7>,
Fleming & Calabrese (2017) <doi:10.1111/2041-210X.12673>,
Péron et al (2017) <doi:10.1002/ecm.1260>,
Fleming et al (2017) <doi:10.1016/j.ecoinf.2017.04.008>,
Fleming et al (2018) <doi:10.1002/eap.1704>,
Winner & Noonan et al (2018) <doi:10.1111/2041-210X.13027>,
Fleming et al (2019) <doi:10.1111/2041-210X.13270>,
and
Noonan & Fleming et al (2019) <doi:10.1186/s40462-019-0177-1>.","taoofcoffee
")


pkgs_short[nrow(pkgs_short) + 1,]<-c("moveHMM","Animal Movement Modelling using Hidden Markov Models","Provides tools for animal movement modelling using hidden Markov
models. These include processing of tracking data, fitting hidden Markov models
to movement data, visualization of data and fitted model, decoding of the state
process...
","taoofcoffee
")
pkgs_short[nrow(pkgs_short) + 1,]<-c("adehabitat","Analysis of Habitat Selection by Animals","A collection of tools for the analysis of habitat selection by animals.","taoofcoffee")

pkgs_short[nrow(pkgs_short) + 1,]<-c("landscapemetrics","Calculates landscape metrics for categorical landscape patterns in a tidy workflow.", "landscapemetrics reimplements the most common metrics from
FRAGSTATS (<https://www.umass.edu/landeco/research/fragstats/fragstats.html>) and new ones from the current literature on landscape metrics.This package supports raster spatial objects and takes
RasterLayer, RasterStacks, RasterBricks or lists of RasterLayer from the raster package as input arguments. It further provides utility functions
to visualize patches, select metrics and building blocks to develop new
metrics.","taoofcoffee")

pkgs_short[nrow(pkgs_short) + 1,]<-c("amt","Animal Movement Tools","Manage and analyze animal movement data. The functionality of 'amt' includes methods to calculate track statistics (e.g. step lengths, speed, or turning angles), prepare data for fitting habitat selection analyses (resource selection functions and step-selection functions <doi:10.1890/04-
0953> and integrated step-selection functions <doi:10.1111/2041-210X.12528>), and simulation of space-use from fitted step-selection functions <doi:10.1002/ecs2.1771>.","BenMMarshall")

pkgs_short[nrow(pkgs_short) + 1,]<-c("adehabitatHR","Home Range Estimation","A collection of tools for the estimation of animals home range.","BenMMarshall")

pkgs_short[nrow(pkgs_short) + 1,]<-c("momentuHMM","Maximum Likelihood Analysis of Animal Movement Behavior Using
Multivariate Hidden Markov Models","Extended tools for analyzing telemetry data using generalized hidden Markov models. Features of momentuHMM (pronounced ``momentum'') include data pre-processing and visualization, fitting HMMs to location and auxiliary biotelemetry or environmental data, biased and correlated random walk movement models, hierarchical HMMs, multiple imputation for incorporating location measurement error and missing data, user-specified design matrices and constraints for covariate modelling of parameters, random effects, decoding of the state process, visualization of fitted models, model checking and selection, and simulation. See McClintock and Michelot (2018) <doi:10.1111/2041-210X.12995>","BenMMarshall")

pkgs_short[nrow(pkgs_short) + 1,]<-c("recurse","Computes Revisitation Metrics for Trajectory Data
","Computes revisitation metrics for trajectory data, such as the number of revisitations for each location as well as the time spent for that visit and the time since the previous visit. Also includes functions to plot data.
","BenMMarshall")

pkgs_short[nrow(pkgs_short) + 1,]<-c("MLWIC2","Machine Learning for Wildlife Image Classification","MLWIC2 can be used to automatically classify camera trap images or to train new models for image classification, it contains two pre-trained models: the species_model identifies 58 species and empty images, and the empty_animal model distinguishes between images with animals and those that are empty. MLWIC2 also contains Shiny apps for running the functions. These can be accessed using runShiny. In the steps below, you can see Shiny options for some steps. This indicates that you can run these steps with Shiny apps by running the function provied. Note that when you are using Shiny apps to select directories and files, you can only navigate using the top part half of the screen and you must scroll to the bottom of the window to find the Select button.","Thorbjörn Sievert")

```

```{r add All Ecology Packages, echo=FALSE}
AllEcologyPackages <-readxl::read_excel("data/AllEcologyPackages.xlsx")
#names(pkgs_short)
names(AllEcologyPackages)<-c("Name", "Short Description", "Long Description")
AllEcologyPackages$Source="Russell Gray"

pkgs_short<-rbind(pkgs_short,AllEcologyPackages)

pkgs_short=pkgs_short %>% 
  distinct(Name, .keep_all = TRUE)%>% drop_na

```


```{r, echo=FALSE}
#pkgs_short %>% select(Name) %>% 
#  duplicated()
# pkgs_short %>% 
#   kable() %>% 
#   kable_styling()
DT::datatable(pkgs_short)
```

